"""
PostToolUse hook: catch forbidden buy/sell/investment language on direct
Write/Edit of the property research notes, not just on script-generated
notes.

Why this exists (see docs/decision_log.md Decision 016 and CLAUDE.md):
scripts/create_property_research_notes.py already refuses to *write* a note
containing forbidden language. But that check only runs when the note is
generated by that script. If a research note (or the script itself) is
edited directly through Write/Edit, the guardrail in the script is bypassed
entirely. This hook re-runs the same check at the point of every
Write/Edit to those files, regardless of how the edit was made.

Reads the standard PostToolUse hook JSON on stdin:
  {"tool_name": "...", "tool_input": {"file_path": "..."}, "tool_response": {...}}

Emits nothing (exit 0, silent) when the edited file is out of scope.
Emits a JSON "decision": "block" response (still exit 0 — this is advisory,
not a hard stop) when forbidden language is found, so Claude sees the
warning and can fix it in the same turn.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

# Patterns are now read from config/forbidden_language.yml (Decision 017),
# the same file scripts/create_property_research_notes.py reads, so the two
# checks cannot drift apart. This import only needs PyYAML, not pandas, so
# the hook stays fast to invoke on every edit.
from src.config import load_forbidden_language_patterns  # noqa: E402

FORBIDDEN_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in load_forbidden_language_patterns()
]

# Files this hook guards: the generated notes themselves, plus the script
# that generates them (so an edit introducing a forbidden literal into a
# template string is also caught before it can ever be run).
GUARDED_PATTERNS = [
    re.compile(r"outputs[/\\]property_research_notes[/\\].*\.md$"),
    re.compile(r"scripts[/\\]create_property_research_notes\.py$"),
]


def is_guarded_path(file_path: str) -> bool:
    normalized = file_path.replace("\\", "/")
    return any(pattern.search(normalized) for pattern in GUARDED_PATTERNS)


def check_forbidden_language(text: str) -> list[str]:
    return [pattern.pattern for pattern in FORBIDDEN_PATTERNS if pattern.search(text)]


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return

    tool_input = payload.get("tool_input", {}) or {}
    tool_response = payload.get("tool_response", {}) or {}
    file_path = tool_input.get("file_path") or tool_response.get("filePath")

    if not file_path or not is_guarded_path(file_path):
        return

    path = Path(file_path)
    if not path.exists():
        return

    text = path.read_text(encoding="utf-8", errors="replace")
    matches = check_forbidden_language(text)

    if not matches:
        return

    result = {
        "decision": "block",
        "reason": (
            f"Forbidden buy/sell/investment language {matches} found in "
            f"{file_path} after a direct Write/Edit. This project's "
            "guardrail (see CLAUDE.md, docs/decision_log.md Decision 015/016) "
            "requires these phrases never appear in research notes, even in "
            "negated disclaimers. Reword the flagged text before continuing."
        ),
        "systemMessage": f"Forbidden language check failed for {file_path}: {matches}",
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
